### ISSUE TITLE
Publish aframe to elm packages

### ISSUE THREAD

**Issue by tilmans** [halfzebra/elm-aframe#7]
What is still needed to publish the elm-aframe lib? Since the DOM updates work now to me it seems to be useful already.

**Comment by halfzebra** [comment]
@tilmans fair enough, I will dedicate my time to publish this package asap. 👍

**Comment by halfzebra** [comment]
@tilmans it's published 🎉

**Comment by tilmans** [comment]
yay! 🤘🏽
