### ISSUE TITLE
1.1.0 release missing assetitem node type

### ISSUE THREAD

**Issue by tilmans** [halfzebra/elm-aframe#9]
Looks like the 1.1.0 release was not made from master? It's missing the `assetitem` node which is available in https://github.com/tilmans/elm-aframe/blob/master/src/AFrame/Primitives.elm 

Please publish 1.2.0 :)

**Comment by halfzebra** [comment]
@tilmans Thanks for the issue, missed a couple commits. I have updated the package and released the new version! 🎉 

`assetitem` is renamed to use camel case.
